services:
  ubuntu-rdp:
    build:
      context: .
    container_name: ubuntu-rdp
    ports:
      - "3389:3389"
    # The CMD is in the Dockerfile, but you can override if needed:
    # command: ["/usr/sbin/xrdp", "--nodaemon"]
